### ISSUE TITLE
Sugerencia: Añadir número máximo de preguntas

### ISSUE THREAD

**Issue by Juanakin18** [gitblanc/Preguntator#1]
Abro esta issue para sugerir la adición de la opción de establecer un número concreto de preguntas que extraer del documento introducido.
Principalmente hago esta sugerencia porque es una funcionalidad sencilla y podría resultar una buena adición a la página.

**Comment by gitblanc** [comment]
Buenas @Juanakin18, acabo de implementar la funcionalidad que sugieres. Te adjunto una captura para ver si te gusta y la entiendes:
<img width="1278" alt="image" src="https://github.com/gitblanc/Preguntator/assets/87705461/d0b19fce-3794-4559-857b-2d2ee8e911ac">
